In [63]:
import numpy as np

In [64]:
#python list
list1 = [1,2,3,4,5,6]

In [65]:
#numpy array
np_array = np.array([1,2,3,4,5,6])

In [66]:
scaler = np.array(90)
print(scaler)

90


In [67]:
vector = np.array([1,2,3,4,5,6])
print(vector)

[1 2 3 4 5 6]


In [68]:
matris = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(matris)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [69]:
py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np_array.reshape(2,3)
print(py_multi)
print(np_multi)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]]


In [70]:
print(np_array.ndim)   #ndim : number of dimensions
print(np_multi.ndim)

1
2


In [71]:
print(np_array.shape)
print(np_multi.shape)

(6,)
(2, 3)


In [72]:
tensor = np.array([[[[4,7,8],[4,5,6]] , [[4,7,8],[4,5,6]] , [[4,7,8],[4,5,6]] ]])
print(tensor)

[[[[4 7 8]
   [4 5 6]]

  [[4 7 8]
   [4 5 6]]

  [[4 7 8]
   [4 5 6]]]]


In [73]:
import time

In [74]:
t1 = time.time()

list1 = []
for a in range(100000):
  list1.append(a**20)

t2 = time.time()
print(t2-t1)

0.07680320739746094


In [75]:
t3 = time.time()

list2 = np.arange(100000)**2

t4 = time.time()

print(t4-t3)

0.001829385757446289


## **Index - Slice**

In [76]:
vector2 = np.array([1,2,3,4,5,6,7,8,9])

In [77]:
vector2[0]

1

In [78]:
vector2[-1]

9

In [79]:
vector2[1:5]

array([2, 3, 4, 5])

In [80]:
vector2[:5]

array([1, 2, 3, 4, 5])

In [81]:
vector2[2:4]

array([3, 4])

In [82]:
vector2[0:8:2]

array([1, 3, 5, 7])