In [2]:
import numpy as np

In [3]:
number1 = np.random.randint(10,100,6)
number2 = np.random.randint(10,100,6)
print(number1)
print(number2)

result = number1 + number2
print(result)

result2 = number1 + 10
print(result2)

[43 79 49 29 44 72]
[63 97 77 55 71 52]
[106 176 126  84 115 124]
[53 89 59 39 54 82]


In [4]:
print(np.sin(number1))
print(np.cos(number1))
print(np.sqrt(number1))
print(np.log(number1))

[-0.83177474 -0.44411267 -0.95375265 -0.66363388  0.01770193  0.25382336]
[ 0.5551133  -0.89597095  0.30059254 -0.74805753  0.99984331 -0.96725059]
[6.55743852 8.88819442 7.         5.38516481 6.63324958 8.48528137]
[3.76120012 4.36944785 3.8918203  3.36729583 3.78418963 4.27666612]


In [5]:
multinumber1 = np.random.randint(10,100,6)
multinumber2 = np.random.randint(10,100,6)
print(multinumber1)
print(multinumber2)

print(multinumber1.reshape(2,3))
print(multinumber2.reshape(2,3))

[41 55 46 77 71 91]
[70 70 44 28 70 65]
[[41 55 46]
 [77 71 91]]
[[70 70 44]
 [28 70 65]]


In [6]:
result3 = np.vstack((multinumber1,multinumber2))  # vertical stack creates a 2D array
print(result3)

[[41 55 46 77 71 91]
 [70 70 44 28 70 65]]


In [7]:
result4 = np.hstack((multinumber1,multinumber2))  # horizontal stack creates a single 1D array
print(result4)

[41 55 46 77 71 91 70 70 44 28 70 65]


In [8]:
result5 = multinumber1 % 2 ==0
print(result5)

[False False  True False False False]


In [9]:
result6 = multinumber1 >=50
print(result6)

[False  True False  True  True  True]


In [10]:
print(multinumber1[result5])  # multinumber1 için result5 değerlerini yazdırır

[46]


In [11]:
print(multinumber1[result6])

[55 77 71 91]
