In [17]:
import numpy as np

In [18]:
result = np.array([1,3,5,7,9])
print(result)

[1 3 5 7 9]


In [19]:
result1 = np.arange(1,10)  #listeyi otomatik olarak oluşturur,yazmamıza gerek kalmaz
print(result1)

[1 2 3 4 5 6 7 8 9]


In [20]:
result2 = np.arange(10,100,3)
print(result2)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [21]:
result3 = np.zeros(10)  #float
print(result3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
result4 = np.ones(10)   #float
print(result4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
#belli bir aralıkta ve eşit artışa sahip bir dizi : linspace(linear space)
result5 = np.linspace(0,100,5)
print(result5)

[  0.  25.  50.  75. 100.]


In [24]:
result6 = np.random.randint(1,10)
print(result6)

7


In [25]:
result7 = np.random.randint(20)  # 0 - 20
print(result7)

16


In [26]:
result8 = np.random.randint(0,10,3)  # 0 - 20
print(result8)

[0 2 6]


In [27]:
result9 = np.random.rand(5)  # between 0 and 1
print(result9)

[0.56571577 0.06963334 0.5559539  0.52159773 0.53949089]


In [28]:
result10 = np.random.randn(5)  # between 0-1  +  negative numbers
print(result10)

[ 0.5762501  -0.89764255 -0.10646805 -1.32157625 -0.46644634]


In [29]:
np_array = np.arange(50)
print(np_array)
np_multi = np_array.reshape(5,10)     # 5 row , 10 column
print(np_multi)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [30]:
print(np_multi.sum(axis=1))  #sum of rows

[ 45 145 245 345 445]


In [31]:
print(np_multi.sum(axis=0))  #sum of columns

[100 105 110 115 120 125 130 135 140 145]


In [32]:
rnd_numbers = np.random.randint(0,10,5)
print(rnd_numbers)

print(rnd_numbers.max())
print(rnd_numbers.min())
print(rnd_numbers.mean())
print(rnd_numbers.argmax())  #Argument of the Maximum (index)
print(rnd_numbers.argmin())  #Argument of the Minimum (index)

[7 2 1 2 5]
7
1
3.4
0
2
