In [1]:
import numpy as np

In [2]:
result = np.array([10,15,20,25,30])
print(result)

[10 15 20 25 30]


In [3]:
result2 = np.arange(5,15)
print(result2)

[ 5  6  7  8  9 10 11 12 13 14]


In [4]:
result3  = np.arange(50,100,5)
print(result3)

[50 55 60 65 70 75 80 85 90 95]


In [5]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
result4 = np.linspace(0,100,5)  # linspace (lineer space): eşit aralıklarla 5 tane sayı üret
print(result4)

[  0.  25.  50.  75. 100.]


In [8]:
result5 = np.random.randint(10,30,5)
print(result5)

[24 22 10 21 22]


In [9]:
result6 = np.random.rand(10)  # rand :  0- 1 arasında 10 tane sayı
print(result6)

[0.37859999 0.28324636 0.33473199 0.76894779 0.39476133 0.23557648
 0.62048814 0.23272079 0.1926776  0.20091264]


In [10]:
result7 = np.random.randn(10)  # randn : -1 - 1 arasında 10 tane sayı
print(result7)

[ 0.35125402 -0.34521631 -1.73006749  0.44169113 -0.74620884 -1.17644903
  0.67596988  0.21582758  1.08772198 -0.85225846]


In [11]:
result8 =  np.random.randint(10,50,15)  # (3x5) bir batris oluşturmak
print(result8)

print(result8.reshape(3,5))

[16 31 23 41 15 11 32 21 29 28 33 14 21 33 16]
[[16 31 23 41 15]
 [11 32 21 29 28]
 [33 14 21 33 16]]


In [12]:
result9 =  np.random.randint(1,100,9).reshape(3,3)
print(result9)

[[96  4 77]
 [84 58 33]
 [51 60  5]]


In [13]:
matris =  np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis=1)  # satır toplamları
columnTotal = matris.sum(axis=0) #sütun toplamları
print(rowTotal)
print(columnTotal)

[125 175 138]
[113  94  85  82  64]


In [14]:
print(matris.max())
print(matris.min())
print(matris.mean())

46
11
29.2


In [15]:
print(matris.argmax())  # index
print(matris.argmin())

7
14


In [16]:
result10 = np.arange(10,20)
print(result10)
print(result10[:3])   #ilk üç eleman
print(result10[::-1]) #elemanları tersten yazdır

[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]


In [17]:
matris =  np.random.randint(10,50,15).reshape(3,5)
print(matris)
print(matris[0])  #matrisin ilk satırı
print(matris[1 , 2])  # 2.satır ,3.sütundaki eleman
print(matris[: , 0])
print(matris**2)

result11 = matris %2 == 0
print(matris [result11])


odd = matris [matris %2 == 1]
print(odd)


[[19 47 39 39 47]
 [19 34 46 14 34]
 [40 46 27 41 18]]
[19 47 39 39 47]
46
[19 19 40]
[[ 361 2209 1521 1521 2209]
 [ 361 1156 2116  196 1156]
 [1600 2116  729 1681  324]]
[34 46 14 34 40 46 18]
[19 47 39 39 47 19 27 41]
