In [1]:
import numpy as np

In [2]:
np_array = np.array([0,5,10,15,20,25,50,75])

In [3]:
print(np_array[4])

20


In [4]:
print(np_array[0:3])
print(np_array[:3])
print(np_array[3:])
print(np_array[::])
print(np_array[::-1])
print(np_array[::-2])

[ 0  5 10]
[ 0  5 10]
[15 20 25 50 75]
[ 0  5 10 15 20 25 50 75]
[75 50 25 20 15 10  5  0]
[75 25 15  5]


In [5]:
np_array2 = np.array([[0,5,10],[15,20,25],[50,75,85]])
print(np_array2[0])
print(np_array2[1])
print(np_array2[2])
print(np_array2[0 , 2])
print(np_array2[1 , 1])
print(np_array2[2 , 2])
print(np_array2[:])      # tüm satırlar
print(np_array2[: ,2])   # tüm satırlardaki 2.index elemanları [10,25,85]
print(np_array2[: ,0])   # tüm satırlardaki 0.index elemanları [0,15,50]
print(np_array2[: ,0:2]) # tüm satırlardaki 0 ile 1.index elemanları
print(np_array2[2 , :])  # 2.satırdaki tüm elemanlar [50 75 85]
print(np_array2[:2 , :2])
print(np_array2[:1 , :2])

[ 0  5 10]
[15 20 25]
[50 75 85]
10
20
85
[[ 0  5 10]
 [15 20 25]
 [50 75 85]]
[10 25 85]
[ 0 15 50]
[[ 0  5]
 [15 20]
 [50 75]]
[50 75 85]
[[ 0  5]
 [15 20]]
[[0 5]]


In [6]:
arr1 = np.arange(0,10)
arr2 = arr1  #aynı adresi gösteren iki farklı değer (referans kopyalaması)

In [7]:
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr1[0] = 20
print(arr1)
print(arr2)

[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]


In [9]:
arr3 = np.arange(0,10)
arr4 = arr3.copy()   # arr3 ve kopyası olan arr4 için farklı adresler oluşturulur
print(arr3)
print(arr4)

arr3[0] = 20
print(arr3)
print(arr4)

arr4[0] = 30
print(arr3)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
[30  1  2  3  4  5  6  7  8  9]
